config/routes.rb
Pipeline::Application.routes.draw do
  namespace :api do
    resource :build_status, only: :create
    delete "projects/:name" => "projects#destroy"
    resource :build, only: [] do
      collection do
        post :lock
        post :unlock
      end
    end
  end

  resources :projects
  root :to => 'projects#index'
end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :revisions, dependent: :destroy
  after_initialize :set_name

  validates :name, presence: true

  def self.all_sorted
    order("position ASC, name ASC")
  end

  def self.find_or_create_for_repository(repository)
    where(repository: repository).first_or_create!
  end

  def latest_revisions(limit = 10)
    revisions.order('id desc').limit(limit)
  end

  def github_wiki_url
    if github_url
      "#{github_url}/wiki"
    else
      nil
    end
  end

  def github_url
    if repository.to_s.include?("github.com")
      match = repository.match(/github.com:(.*?)\./)
      github_path = match && match[1]
      "https://github.com/#{github_path}"
    else
      nil
    end
  end

  private

  def set_name
    return unless repository
    self.name ||= repository.split("/").last.split(".").first
  end
end

app/models/repository/memory/project.rb
require 'repository/memory/mapper'
require 'repository/common/project'

module Repository
  class Memory::Project < Memory::Mapper
    include Repository::Common::Project
  end
end

app/models/repository/pg/project.rb
require 'repository/pg/mapper'
require 'repository/common/project'

module Repository
  class PG::Project < PG::Mapper
    include Repository::Common::Project
    entity_klass Project

    private

    def record_klass
      Record
    end

    class Record < ActiveRecord::Base
      attr_accessible :name, :github_url, :created_at, :updated_at
      self.table_name = :projects
    end
  end
end

app/controllers/api/projects_controller.rb
class Api::ProjectsController < ApiController
  def destroy
    project = Project.find_by_name(params[:name])
    project.destroy

    PostStatusToWebhook.call(project)

    render text: "ok"
  end
end

app/controllers/projects_controller.rb
class ProjectsController < WebController
  before_action :get_projects

  def index
    revision_amount = 2
    locals revision_amount: revision_amount
  end

  def show
    project = Project.find(params[:id])
    revision_amount = 15
    locals :show,
      {revision_amount: revision_amount,
      project: project}
  end

  def edit
    @project = Project.find(params[:id])
  end

  def update
    project = Project.find(params[:id])

    if project.update_attributes(project_params)
      PostStatusToWebhook.call(project)
      redirect_to root_path, notice: "Project updated."
    else
      @project = project
      render :edit
    end
  end

  def destroy
    Project.find(params[:id]).destroy
    redirect_to root_path, notice: "Project removed."
  end

  private

  def project_params
    params.require(:project).permit(:name, :repository, :mappings, :position)
  end

  def setup_menu
    active_menu_item_name :projects
  end

  def get_projects
    @projects = Project.all_sorted
  end
end

app/views/projects/_form.html.haml
.row
  .span12
    .page
      = bootstrap_form_for(@project) do |f|
        = f.text_field :name
        = f.text_field :github_url
        = f.text_field :build_pattern
        .form-actions
          = submit_tag "Save", class: "btn btn-primary"

app/views/projects/_project.html.slim
.actions
  = link_to("Edit", edit_project_path(project))
  - if project.github_url
    = ' | '
    = link_to("Github", project.github_url)
  - if project.github_wiki_url
    = ' | '
    = link_to("Wiki", project.github_wiki_url)
.status
  h1= link_to(project.name, project_path(id: project.id))
  .revisions
    - project.latest_revisions(revision_amount).each do |revision|
      .revision
        - presenter = RevisionPresenter.new(revision)
        = link_to(presenter.name, revision.github_url, target: "_blank")
        - presenter.builds.each do |build|
          span.build class=build.status
            = link_to_if(build.status_url, build.name, build.status_url, target: "_blank")

app/views/projects/edit.html.haml
= render "form"

app/views/projects/edit.html.slim
.row
  .span12
    .page
      .row
        .span9
          = bootstrap_form_for(@project) do |f|
            = f.text_field :name
            = f.text_field :position
            = f.text_area :mappings, style: "width: 875px; height: 400px;", label: "Mappings (ordered aliases for longer build names)"
            p Syntax:
            p= "build_name1=alias1<br/>build_name2=alias2".html_safe
            p If two builds have the same alias, then the results will be merged (e.g. one failed build and one successful build is an overall failure)
            .form-actions
              = submit_tag "Save", class: "btn btn-primary"
        .span2
          p= link_to("Remove project", project_path(@project), method: :delete, data: { confirm: "Are you sure you want to remove #{@project.name}?" })

app/views/projects/index.html.haml
.row
  .span12
    - @projects.each do |project|
      .project[project]
        .actions
          = link_to("Edit", edit_project_path(project))
          |
          = link_to("Remove", project_path(project), method: :delete, confirm: "Are you sure you want to remove #{project.name}?")
          - if project.github_url
            |
            = link_to("Github", project.github_url)
        %h1= project.name
        - # temporary code, want a quick way to view our current build data before building something real
        - if project.build_pattern
          - Build.where("name LIKE ?", project.build_pattern).order("id desc").each do |build|
            %p= "#{build.name} #{build.revision} #{build.status}"

app/views/projects/index.html.slim
.row.index
  .span12
    - @projects.each do |project|
      .project id="project_#{project.id}"
        = render "project", project: project, revision_amount: revision_amount

app/views/projects/new.html.haml
= form_for(@project, url: projects_path) do |f|
  - if @project.errors.any?
    = @project.errors.full_messages.each do |error|
      %p{style: 'color: red'}= error
  = f.label :name
  = f.text_field :name
  = f.label :github_url
  = f.text_field :github_url
  = f.submit "Save"

app/views/projects/show.html.slim
.row
  .span12
    .project id="project_#{project.id}"
      = render "project", project: project, revision_amount: revision_amount