config/routes.rb
Pipeline::Application.routes.draw do
  namespace :api do
    resource :build_status, only: :create
    delete "projects/:name" => "projects#destroy"
    resource :build, only: [] do
      collection do
        post :lock
        post :unlock
      end
    end
  end

  resources :projects
  root :to => 'projects#index'
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Deployer

  = stylesheet_link_tag "application", media: "all"
  = javascript_include_tag "application"
  = csrf_meta_tags

  %body
    .container
      .navbar
        .navbar-inner
          = link_to("Deployer", root_path, class: "brand")
          %ul.nav
            %li[menu_item(:projects)]
              = link_to("Projects", projects_path)
            %li[menu_item(:new_project)]
              = link_to("Add project", new_project_path)


    .container
      - if flash[:notice]
        %p.alert.alert-success= flash[:notice]
      = yield

app/views/layouts/application.html.slim
html
  head
    title Pipeline

  = stylesheet_link_tag "application", media: "all"
  = javascript_include_tag "application"
  = csrf_meta_tags

  body
    .container
      .navbar
        .navbar-inner
          = link_to("Pipeline", root_path, class: "brand")
          ul.nav
            - @projects.each do |project|
                li class=menu_item_class(:projects)
                  = link_to(project.name, project_path(id: project.id))


    .container
      - if flash[:notice]
        p.alert.alert-success= flash[:notice]
      = yield